theme: jekyll-theme-minimal
logo: /me.jpg
title: Anissa Ng's site
description: Get to know me! 

# Hello! I'm Anissa.
Final year law student at CUHK. Passionate about technology and innovation.
### Education
*Major in Law, Minor in Entrepreneurship and Innovation @ CUHK
*Year-long exchange @ UC Berkeley

### Projects
*Currently enrolled in EPIN1020, check out [my repository for the course](https://an-yc.github.io/epin1020/)
*Working on a campus project, CUHub

### Experience
*I have interned at various law firms, including Sidley Austin and BCLP.
*I am currently looking into opportunties for this summer in the tech and start-up field
