theme: jekyll-theme-minimal

title: Anissa Ng's site
# Hi, I'm Anissa
Final year law student at CUHK. Passionate about technology and innovation.

## Education
Bachelor of Laws, Minor in Entrepreneurship and Innovation @ CUHK
Year-long exchange @ UC Berkeley

## Projects 
Currently enrolled in EPIN2010, check out [my repository for the course](https://an-yc.github.io/epin1020/)
Working on a campus project, CUHub

## Experience 
I've interned at various law firms, including Sidley Austin and BCLP. I am currently looking into opportunties for this summer in the tech and start-up field

